#!/usr/bin/env perl
use 5.14.0;
use warnings;
use Carp;

use Perl5::Build::Warnings;
use Getopt::Long;
use Data::Dump qw(dd pp);

my ($dumbquotes) = ('') x 1;
GetOptions("dq" => \$dumbquotes)
    or croak "Error in command line arguments\n";

croak "Must provide path to 'make' output"
    unless @ARGV;

my @inputs = @ARGV;
for (@inputs) {
    croak "Cannot locate file '$_'" unless -f $_;
}

for my $f (@inputs) {
    say "File:  $f";
    say '';
    my $self = Perl5::Build::Warnings->new( { file => $f } );
    my $aref = $self->get_warnings;
    unless ($dumbquotes) {
        dd $aref;
    }
    else {
        my @cleaned = ();
        for my $w ( @$aref ) {
            my $cleaned = { map { $_ => $w->{$_} } keys %{$w} };
            ($cleaned->{text}) = $w->{text} =~ s{(
                \xE2\x80\x98 |
                \xE2\x80\x99
            )}
            {"}grx;
            push @cleaned, $cleaned;
        }
        dd [ @cleaned ];
    }
    say '';
}
